# Generated by Django 3.1.7 on 2021-06-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computers',
            options={'ordering': ['make'], 'verbose_name': 'Computer'},
        ),
        migrations.AddField(
            model_name='computers',
            name='category',
            field=models.CharField(blank=True, choices=[('desktop', 'desktop'), ('laptob', 'laptob')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='computers',
            name='config',
            field=models.TextField(default='CPU : \nGPU : \nRAM : ', max_length=9999),
        ),
        migrations.AlterField(
            model_name='computers',
            name='image',
            field=models.ImageField(blank=True, default='images/21/06/06/sfd.jpeg', null=True, upload_to='images/%y/%m/%d'),
        ),
    ]
