# Generated by Django 3.1.7 on 2021-06-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_test_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computers',
            options={'verbose_name': 'Computer'},
        ),
    ]
